.MODEL SMALL
.STACK 100h
pulalinha MACRO
    mov ah, 02h           
    mov dl, 13        
    Int 21h               
    mov dl, 10          
    int 21h
endm   
.DATA
MATRIZ4X4 DB 4 dup(4 dup(?))
MSG DB 'A MATRIZ EH:$'
MSG2 DB 10,13,'A SOMA EH:$'
.CODE
MAIN PROC
MOV AX,@DATA
MOV DS,AX
MOV CX,16 ;CX FUNCIONARA COMO CONTADOR PARA SABER A HORA DE PARAR DELER A MATRIZ
XOR SI,SI ;INICIALIZA SI
CALL LERO
XOR SI,SI
XOR BX,BX
MOV CX,16
pulalinha
MOV AH,09
LEA DX,MSG
INT 21H
CALL IMP ; CHAMA O PROCEIDMENTO IMP
MOV AH,09
LEA DX,MSG2
INT 21H
CALL soma

FIM:
MOV AH,4CH
INT 21h
MAIN ENDP 

LER PROC

LERO:
MOV AH,01                 ;LE
INT 21h 
MOV MATRIZ4X4[BX][SI],AL         
INC SI                    ;AUMENTA O VALOR DA COLUNA
DEC CX                    ;DIMINUI O CONTADOR
CMP CX,0                  ;COMPARA COM CX, SE FOR 0 ACABA
JE FINAL                  ;SE IGUAL ENCERRA
CMP SI,4                  ;COMPARA COM 4 PRA VER SE É A HORA DE PULAR LINHA
JNE LERO              ;SE NÃO VOLTA AO LOOP
ADD BX,4                  ;SE SIM ADICIONA 4 EM BX, MUDANDO A LINHA DA MATRIZ
XOR SI,SI                 ;ZERA SI PRA VOLTARMOS NA COLUNA 0
pulalinha                 ;MACRO DE PULAR LINHA
JMP LERO             ;VOLTA NO LOOP
FINAL:
RET 
LER ENDP

IMP PROC
pulalinha
IMPRIMIR:
MOV AH,02                 ;IMPRIMI
MOV DL,MATRIZ4X4[BX][SI] 
INT 21h          
INC SI                    ;AUMENTA O VALOR DA COLUNA
DEC CX                    ;DIMINUI O CONTADOR
CMP CX,0                  ;COMPARA COM CX, SE FOR 0 ACABA
JE FIMA                   ;SE IGUAL ENCERRA
CMP SI,4                  ;COMPARA COM 4 PRA VER SE É A HORA DE PULAR LINHA
JNE IMPRIMIR              ;SE NÃO VOLTA AO LOOP
ADD BX,4                  ;SE SIM ADICIONA 4 EM BX, MUDANDO A LINHA DA MATRIZ
XOR SI,SI                 ;ZERA SI PRA VOLTARMOS NA COLUNA 0
pulalinha                 ;MACRO DE PULAR LINHA
JMP IMPRIMIR              ;VOLTA NO LOOP
FIMA:
RET 
IMP ENDP

soma PROC
XOR AL,AL
op:
ADD AL,MATRIZ4X4[BX][SI] ;CARACTER ASCII
INC SI                    ;AUMENTA O VALOR DA COLUNA
DEC CX                    ;DIMINUI O CONTADOR
CMP CX,0                  ;COMPARA COM CX, SE FOR 0 ACABA
JE lep                   ;SE IGUAL ENCERRA
CMP SI,4                  ;COMPARA COM 4 PRA VER SE É A HORA DE PULAR LINHA
JNE op             ;SE NÃO VOLTA AO LOOP
ADD BX,4                  ;SE SIM ADICIONA 4 EM BX, MUDANDO A LINHA DA MATRIZ
XOR SI,SI                 ;ZERA SI PRA VOLTARMOS NA COLUNA 0
JMP op             ;VOLTA NO LOOP
lep:
XOR AH,AH
XOR BX,bx
MOV BX,10
XOR CX,CX
DIVISAO:
CMP AX,BX
INC CX
JBE ULTIMO
DIV BX
PUSH DX
JMP DIVISAO
ULTIMO:
IMPRIMAIR:
MOV DX,AX
ADD DX,30H
MOV AH,02
ADD DX,30H
INT 21H
XOR DX,DX
POP AX
LOOP IMPRIMAIR
RET 
soma ENDP
END MAIN