.MODEL SMALL
.STACK 100h
pulalinha MACRO
    mov ah, 02h           
    mov dl, 13        
    Int 21h               
    mov dl, 10          
    int 21h
endm   
.DATA
MATRIZ4X4 DB 1, 2, 3, 4
          DB 4, 3, 2, 1
          DB 5, 6, 7, 8
          DB 8, 7, 6, 5
.CODE
MAIN PROC
MOV AX,@DATA
MOV DS,AX
MOV CX,16 ;CX FUNCIONARA COMO CONTADOR PARA SABER A HORA DE PARAR DE IMPRIMIR A MATRIZ
XOR SI,SI ;INICIALIZA SI
CALL IMP ; CHAMA O PROCEIDMENTO IMP

MOV AH,4CH
INT 21h
MAIN ENDP 

IMP PROC

IMPRIMIR:
ADD MATRIZ4X4[BX][SI],30H ;CARACTER ASCII
MOV AH,02                 ;IMPRIMI
MOV DL,MATRIZ4X4[BX][SI] 
INT 21h          
INC SI                    ;AUMENTA O VALOR DA COLUNA
DEC CX                    ;DIMINUI O CONTADOR
CMP CX,0                  ;COMPARA COM CX, SE FOR 0 ACABA
JE FIM                    ;SE IGUAL ENCERRA
CMP SI,4                  ;COMPARA COM 4 PRA VER SE É A HORA DE PULAR LINHA
JNE IMPRIMIR              ;SE NÃO VOLTA AO LOOP
ADD BX,4                  ;SE SIM ADICIONA 4 EM BX, MUDANDO A LINHA DA MATRIZ
XOR SI,SI                 ;ZERA SI PRA VOLTARMOS NA COLUNA 0
pulalinha                 ;MACRO DE PULAR LINHA
JMP IMPRIMIR              ;VOLTA NO LOOP
FIM:
RET 
IMP ENDP
END MAIN