.MODEL SMALL
.STACK 100h
.DATA
 MSG1 DB 'DIGITE SEU NOME$'
MSG2 DB 10,13, 'O NUMERO DE VOGAIS eh:$'
VOGA DB ?
.CODE
MAIN PROC
    @LOOP_LEITURA1:
        MOV AH,01
        INT 21H
        CMP AL,13
        JE @SAI_LEITURA1     ;SE É ENTER ENTÃO SAI
        AND  AX, 0FH        ;TRANSFORMA EM NUMERO
        PUSH AX             ;GUARDA VALOR ANTES DA OPERACAO
        MOV AX,10           ;MOVE MULTIPLICADOR PARA AX
        MUL DX              ;FAZ AX x BX
        POP DX              ;DEVOLVE O VALOR PARA BX
        ADD DX,AX           ;ADCIONA O VALOR ANTES LIDO AGORA DO VALOR TOTAL (BX = BX + (BX x AX))
        JMP @LOOP_LEITURA1
        @SAI_LEITURA1:
    MOV SI,DX
 MOV AH,4CH
    INT 21h
    MAIN ENDP
    END MAIN